version: 2
jobs:
  build:
    docker:
    - image: alpine:3.7
    steps:
    - run:
        name: The First Step
        command: |
          echo 'Hello World!'
          echo 'This is the delivery pipeline'
workflows:
  version: 2
  workflow:
    jobs:
    - build

# Original config.yml file:
# version: 2.1
# jobs:
#   build:
#     docker:
#       - image: alpine:3.7
#     steps:
#       - run:
#           name: The First Step
#           command: |
#             echo 'Hello World!'
#             echo 'This is the delivery pipeline'