version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13
  cypress: cypress-io/cypress@1.8.0

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
