version: 2.1

orbs:
  # aws-cli: circleci/aws-cli@0.1.13
  # cypress: cypress-io/cypress@1.8.0

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: yarn install
          command: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Build app
          command: yarn build

      - persist_to_workspace:
          root: ~/repo
          paths:
            - build
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: Install and configure dependencies
          command: |
            yarn add gh-pages -D
            git config user.email "ts.roberto@gmail.com"
            git config user.name "maninkari"
      - add_ssh_keys:
          fingerprints:
            - '34:39:64:df:51:6d:38:ec:57:77:d0:61:4b:6b:ff:34'
      - run:
          name: Deploy docs to gh-pages branch
          command: './node_modules/.bin/gh-pages --dotfiles --message "[skip ci] Updates" -d build'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_test_results:
          path: test-results.xml
