version: 2.1

orbs:
  cypress: cypress-io/cypress@1.24.0
  aws-s3: circleci/aws-s3@1.0.15

jobs:
  cache-dependencies:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: yarn install
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

  build:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Unit tests
          command: yarn test
      - run:
          name: Build app
          command: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - build
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_test_results:
          path: test-results.xml

  deploy_gh:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo
    steps:
      - run:
          name: Deploy
          command: |
            echo 'deploying stuff!'
      # - run:
      #     name: Install and configure dependencies
      #     command: |
      #       yarn add gh-pages -D
      #       git config user.email "ts.roberto@gmail.com"
      #       git config user.name "maninkari"
      # - add_ssh_keys:
      #     fingerprints:
      #       - '34:39:64:df:51:6d:38:ec:57:77:d0:61:4b:6b:ff:34'
      # - run:
      #     name: Deploy docs to gh-pages branch
      #     command: './node_modules/.bin/gh-pages --dotfiles --message "[skip ci] Updates" -d build'

  deploy_dev:
    docker:
      - image: circleci/python:jessie
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - aws-s3/sync:
          from: build
          to: 's3://${S3_BUCKET_DEPLOY_DEV}/'
          arguments: --acl public-read --cache-control "max-age=86400"
          overwrite: true

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - cache-dependencies
      - cypress/run:
          yarn: true
          name: e2e test
          start: 'yarn build && yarn mock'
          wait-on: 'http://localhost:8080'
          command: yarn cypress run --reporter junit --reporter-options 'mochaFile=cypress/results/junit.xml'
          store_artifacts: true
          post-steps:
            - store_test_results:
                path: cypress/results
          filters:
            branches:
              ignore: master
      - deploy_dev:
          requires:
            - cache-dependencies
          filters:
            branches:
              ignore: master
          # context: AWS
