# circleci config validate
version: 2.1

orbs:
  cypress: cypress-io/cypress@1.24.0
  aws-s3: circleci/aws-s3@1.0.15

jobs:
  cache-dependencies:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: yarn install
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

  build:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Unit tests
          command: yarn test
      - run:
          name: Build app
          command: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - build
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_test_results:
          path: test-results.xml

  deploy_dev:
    docker:
      - image: circleci/python:jessie
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - aws-s3/sync:
          from: build
          to: 's3://archetype-react-dev'
          # bucket properties need to be edited or --acl public-read won't work
          arguments: --acl public-read --cache-control "max-age=86400"
          overwrite: true

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - cache-dependencies
      - build
      - cypress/run:
          yarn: true
          name: e2e test
          start: 'yarn build && yarn mock'
          wait-on: 'http://localhost:8080'
          command: yarn cypress run --reporter junit --reporter-options 'mochaFile=cypress/results/junit.xml'
          store_artifacts: true
          post-steps:
            - store_test_results:
                path: cypress/results
          filters:
            branches:
              ignore: master
      - deploy_dev:
          requires:
            - cache-dependencies
            - build
            - e2e test
          filters:
            branches:
              ignore: master
