version: 2.1

orbs:
  cypress: cypress-io/cypress@1.24.0

jobs:
  cache-dependencies:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: yarn install
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - ~/.cache
      - persist_to_workspace:
          root: ~/
          paths:
            - .cache/Cypress

  build:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Unit tests
          command: yarn test
      - run:
          name: Build app
          command: yarn build

      - persist_to_workspace:
          root: ~/repo
          paths:
            - build
      # - run:
      #     name: Install and configure dependencies
      #     command: |
      #       yarn add gh-pages -D
      #       git config user.email "ts.roberto@gmail.com"
      #       git config user.name "maninkari"
      # - add_ssh_keys:
      #     fingerprints:
      #       - '34:39:64:df:51:6d:38:ec:57:77:d0:61:4b:6b:ff:34'
      # - run:
      #     name: Deploy docs to gh-pages branch
      #     command: './node_modules/.bin/gh-pages --dotfiles --message "[skip ci] Updates" -d build'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_test_results:
          path: test-results.xml

  e2e_test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: e2e tests
          command: yarn test:e2e
      - store_artifacts:
          path: e2e-test-results.xml
          prefix: tests
      - store_test_results:
          path: e2e-test-results.xml

  deploy:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo
    steps:
      - run:
          name: Deploy
          command: |
            echo 'deploying stuff!'

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - cache-dependencies
      - build:
          requires:
            - cache-dependencies
          filters:
            branches:
              ignore: master
      - e2e_test:
          requires:
            - cache-dependencies
            - build
          filters:
            branches:
              ignore: master
      - deploy:
          requires:
            - cache-dependencies
          filters:
            branches:
              only: master
          # context: AWS
